id: P57E6D006
initial_creation_type: ocr
source_metadata:
  volumes:
    215c644c2d3d47d6a9579371c96044a6:
      base_file: v057.txt
      image_group_id: I1PD95902
      title: རང་བཞིན་གསུམ་ལ་འཇུག་པའི་སྒྲུབ་པ།
      total_pages: 1605
      volume_number: 57
